"""add suggested reply to message

Revision ID: 19c7226c47e5
Revises: df34b18f907d
Create Date: 2026-09-02 02:42:39.761998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c7226c47e5'
down_revision: Union[str, Sequence[str], None] = 'df34b18f907d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('suggested_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'suggested_reply')
    # ### end Alembic commands ###
