"""add converted to sale field

Revision ID: 26c64f41f4ae
Revises: 26bb9bfc7e15
Create Date: 2026-09-06 03:35:32.295778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c64f41f4ae'
down_revision: Union[str, Sequence[str], None] = '26bb9bfc7e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('converted_to_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'converted_to_sale')
    # ### end Alembic commands ###
