"""add business info to store

Revision ID: 6b95131bc37a
Revises: 19c7226c47e5
Create Date: 2026-09-02 18:02:24.029290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b95131bc37a'
down_revision: Union[str, Sequence[str], None] = '19c7226c47e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('business_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'business_info')
    # ### end Alembic commands ###
