"""add conversations table

Revision ID: 8000a5bfbbfd
Revises: 26c64f41f4ae
Create Date: 2026-09-06 14:24:17.549355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8000a5bfbbfd'
down_revision: Union[str, Sequence[str], None] = '26c64f41f4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('platform', postgresql.ENUM('whatsapp', 'instagram', 'telegram', name='platformenum', create_type=False), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('converted_to_sale', sa.Boolean(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('messages', 'converted_to_sale')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('converted_to_sale', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'conversation_id')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
