"""add is_from_store to message

Revision ID: cbd1b02b8df6
Revises: 8000a5bfbbfd
Create Date: 2026-09-08 15:07:49.986093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd1b02b8df6'
down_revision: Union[str, Sequence[str], None] = '8000a5bfbbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_from_store', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_from_store')
    # ### end Alembic commands ###
