"""add telegram bot token to store

Revision ID: df34b18f907d
Revises: a90828a32a6e
Create Date: 2026-09-02 01:03:20.419821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df34b18f907d'
down_revision: Union[str, Sequence[str], None] = 'a90828a32a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('telegram_bot_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'telegram_bot_token')
    # ### end Alembic commands ###
